// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanSua.Models;

namespace WebBanSua.Migrations
{
    [DbContext(typeof(CuaHangBanSuaContext))]
    partial class CuaHangBanSuaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBanSua.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("date");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("WebBanSua.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCtdh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTDH")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("Ngaygiao")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("MaCtdh")
                        .HasName("PK__ChiTietD__1E4E40F0C7EDC280");

                    b.HasIndex("MaDh");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("WebBanSua.Models.DanhMucSp", b =>
                {
                    b.Property<int>("MaDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnhDm")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhDM");

                    b.Property<string>("MoTaDm")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MoTaDM");

                    b.Property<string>("TenDm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenDM");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDm")
                        .HasName("PK__DanhMucS__2725866EE82E8DAD");

                    b.ToTable("DanhMucSP");
                });

            modelBuilder.Entity("WebBanSua.Models.DonHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDH")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThanhToan")
                        .HasColumnType("bit");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiHuyDon")
                        .HasColumnType("int");

                    b.HasKey("MaDh")
                        .HasName("PK__DonHang__2725866101A47066");

                    b.HasIndex("MaKh");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("WebBanSua.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarKh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AvatarKH");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Diachi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKH");

                  

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1EED6DB3BA");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("WebBanSua.Models.RoleAccount", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("RoleId")
                        .HasName("PK__RoleAcco__8AFACE3A7AB4B914");

                    b.ToTable("RoleAccount");
                });

            modelBuilder.Entity("WebBanSua.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnhSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhSP");

                    b.Property<bool>("BestSeller")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("date");

                    b.Property<int>("GiaSp")
                        .HasColumnType("int")
                        .HasColumnName("GiaSP");

                    b.Property<int?>("MaDm")
                        .HasColumnType("int")
                        .HasColumnName("MaDM");

                    b.Property<string>("MotaSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotaSP");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("date");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenSP");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VideoSp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VideoSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081CBF3C0121");

                    b.HasIndex("MaDm");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("WebBanSua.Models.TinTuc", b =>
                {
                    b.Property<int>("MaTt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnhTt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhTT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("date");

                    b.Property<bool?>("LoaiTin")
                        .HasColumnType("bit");

                    b.Property<string>("Motadai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motangan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tacgia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenTT");

                    b.HasKey("MaTt")
                        .HasName("PK__TinTuc__27250079A6FB35AA");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("WebBanSua.Models.Account", b =>
                {
                    b.HasOne("WebBanSua.Models.RoleAccount", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Account__RoleID__35BCFE0A")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebBanSua.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("WebBanSua.Models.DonHang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh")
                        .HasConstraintName("FK__ChiTietDon__MaDH__36B12243")
                        .IsRequired();

                    b.HasOne("WebBanSua.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK__ChiTietDon__MaSP__37A5467C")
                        .IsRequired();

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanSua.Models.DonHang", b =>
                {
                    b.HasOne("WebBanSua.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__DonHang__MaKH__38996AB5")
                        .IsRequired();

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("WebBanSua.Models.SanPham", b =>
                {
                    b.HasOne("WebBanSua.Models.DanhMucSp", "MaDmNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDm")
                        .HasConstraintName("FK__SanPham__MaDM__3A81B327");

                    b.Navigation("MaDmNavigation");
                });

            modelBuilder.Entity("WebBanSua.Models.DanhMucSp", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebBanSua.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("WebBanSua.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebBanSua.Models.RoleAccount", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("WebBanSua.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
